version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - NEXT_PUBLIC_API_URL=${NEXT_PUBLIC_API_URL}
    ports:
      - "3000:3000"
    environment:
      - API_URL=${API_URL}
      - NEXT_PUBLIC_API_URL=${NEXT_PUBLIC_API_URL}
      - SESSION_MAX_AGE=${SESSION_MAX_AGE}
      - SECURE_COOKIES=${SECURE_COOKIES}
      - ZOOM_SDK_KEY=${ZOOM_SDK_KEY}
      - WITHINGS_CLIENT_ID=${WITHINGS_CLIENT_ID}
    restart: unless-stopped

